# Site Info
title:              "古诗词集"
description:        "The Plain is a minimalist Jekyll theme, that's it. Can't say anymore..."
google_verify:      # Pu your Google Verification here
google_analytics:   UA-98623479-1 # Put your Google Analytics code

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: f7f3cec83288773eed040db6eb0dd64f


# Author Info
author_name:        "夙兴夜寐" # Your name here
author_email:       wscrlhs@gmail.com  # Your email here
author_gravatar:    2b38b1b0e7e08b69379bd61582adf0c8 # Your Gravatar md5 hash here for logo
twitter_username:   #HeiswayiNrird # Your Twitter username here
github_username:    wscrlhs #Your GitHub username here

# Site Settings
url:                http://zhoufuyeben.com # main url
baseurl:            /collection-poems # for gh-pages
blog_url:           http://zhoufuyeben.com # main blog url
permalink:          /poems/:title # Post permalink
timezone:           Asia/Shanghai # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
paginate: 15 
paginate_path: "page:num"
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate




defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
